apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: route-auth
  namespace: auth
spec:
  host: demo.my-f5.com
  upstreams:
  - name: auth
    service: auth-my-f5-com
    port: 80
  subroutes:
  - path: /auth
    action:
      proxy:
        upstream: auth
    location-snippets: | 
      internal;      

      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-URI $request_uri;

      proxy_cache           token_responses; # Enable caching
      proxy_cache_key       $http_apikey;    # Cache for each access token
      proxy_cache_lock      on;              # Duplicate tokens must wait
      proxy_cache_valid     204 60s;         # Cache 204 responses for this many seconds
      proxy_cache_valid     401 300s;         # Cache 401 responses for this many seconds
      proxy_ignore_headers  Cache-Control Expires Set-Cookie;
