apiVersion: v1
kind: Service
metadata:
  name: private-svc
  namespace: private
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
      app: hello-world
